apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: argocd 
  labels:
    app: test
  annotations:
    avp.kubernetes.io/path: "kv/data/app1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test
          image: nginx
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
          - name: VAULT_ENV1
            value: <env1>
          - name: VAULT_ENV2
            value: <env2>
          
