apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: test